# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 152f22ac9c68d51f4d4cde8d2d6ffa034209c19eb21a65b959f960cfdae41d0af586671063ce0f4145bca8a6100bc456ee3e966bf0f4d97e9bd1e91cd03e9640

test:
  secret_key_base: 89c781e1084c395e4d2df217bb547d8ae55aa5325474f9bca257a40342603968be6e7ddec3c34be5d6d700f3c9edf25fcc00e637b79b16567791bc32a1199665

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
